import Link from "next/link";


export default function PrivacyPolicy() {
    return (
        <>
            <section className="pt-30 sm:pt-40 lg:pt-50 pb-8 sm:pb-16 lg:pb-32.5">
                <div className="container">
                    <div className="w-full max-w-312.75 mx-auto space-y-4 sm:space-y-7.5">
                        <div>
                            <h1 className="text-3xl md:text-4xl lg:text-5xl leading-14 mb-2.5 sm:mb-5 text-white">Privacy Policy</h1>
                            <p>Last updated: 01 Februay 2026</p>
                            <p>This Privacy Policy describes the policies and procedures of Beyond Code on the collection, use, and disclosure of Your information when You use our services and websites, and explains Your privacy rights and how applicable laws protect You.</p>
                        </div>
                        <div>
                            <h5>Interpretation</h5>
                            <p className="mt-4">Words with capitalized initials have meanings defined under the following conditions. These definitions apply regardless of whether they appear in singular or plural form.</p>
                        </div>
                        <div>
                            <h5>Definitions</h5>
                            <p className="my-4">For the purposes of this Privacy Policy:</p>
                            <ul className="list-disc pl-6 mt-1">
                                <li>Account means a unique account created for You to access our Service or parts of our Service.</li>
                                <li>Company (referred to as “Beyond Code”, “We”, “Us”, or “Our”) refers to Beyond Code, operating through arclab.ae and beyondcode.ae.</li>
                                <li>Cookies are small files placed on Your computer, mobile device, or any other device by a website, containing details of Your browsing history.</li>
                                <li>Country refers to the countries where Beyond Code operates, including the United Arab Emirates, United Kingdom, and Bangladesh.</li>
                                <li>Device means any device that can access the Service such as a computer, a mobile phone, or a digital tablet.</li>
                                <li>Personal Data is any information that relates to an identified or identifiable individual.</li>
                                <li>Service refers to the Beyond Code websites and related services.</li>
                                <li>Service Provider means any natural or legal person who processes data on behalf of the Company, including third-party vendors engaged to facilitate or analyze the Service.</li>
                                <li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure.</li>
                                <li>Website refers to Beyond Code, accessible from arclab.ae and beyondcode.ae.</li>
                                <li>You means the individual or legal entity accessing or using the Service.</li>
                            </ul>
                        </div>
                        <div>
                            <h5>Collecting and Using Your Personal Data</h5>
                            <h6 className="text-base sm:text-lg sm:leading-6.5 text-white font-semibold my-3 sm:my-4">Types of Data Collected</h6>
                            <h6 className="text-sm sm:text-base sm:leading-5 text-white font-semibold my-3 sm:my-4">Personal Data</h6>
                            <p className="my-3 sm:my-4">While using Our Service, We may ask You to provide certain personally identifiable information that can be used to contact or identify You. This may include, but is not limited to:</p>
                            <ul className="list-disc pl-6 mt-1">
                                <li>First name and last name</li>
                                <li>Email address</li>
                                <li>Phone number</li>
                                <li>Address, city, state/province, ZIP/postal code</li>
                            </ul>
                            <h6 className="text-sm sm:text-base sm:leading-5 text-white font-semibold my-3 sm:my-4">Usage Data</h6>
                            <p className="my-3 sm:my-4">Usage Data is collected automatically when using the Service and may include information such as:</p>
                            <ul className="list-disc pl-6 mt-1">
                                <li>IP address</li>
                                <li>Browser type and version</li>
                                <li>Pages visited and time spent on those pages</li>
                                <li>Date and time of visits</li>
                                <li>Device identifiers and diagnostic data</li>
                            </ul>
                            <p className="mt-3 sm:mt-4">When You access the Service via a mobile device, We may also collect information such as device type, operating system, mobile browser type, and mobile IP address.</p>
                        </div>
                        <div>
                            <h5>Tracking Technologies and Cookies</h5>
                            <h6 className="text-base sm:text-lg sm:leading-6.5 text-white font-semibold my-3 sm:my-4">Types of Cookies We Use</h6>
                            <h6 className="text-sm sm:text-base sm:leading-5 text-white font-semibold my-3 sm:my-4">Necessary / Essential Cookies</h6>
                            <ul className="list-disc pl-6 mt-1">
                                <li>Type: Session Cookies</li>
                                <li>Purpose: Enable core functionality, user authentication, and fraud prevention.</li>
                            </ul>
                            <h6 className="text-sm sm:text-base sm:leading-5 text-white font-semibold my-3 sm:my-4">Cookies Policy / Notice Acceptance Cookies</h6>
                            <ul className="list-disc pl-6 mt-1">
                                <li>Type: Persistent Cookies</li>
                                <li>Purpose: Store Your consent preferences regarding cookies.</li>
                            </ul>
                            <h6 className="text-sm sm:text-base sm:leading-5 text-white font-semibold my-3 sm:my-4">Functionality Cookies</h6>
                            <ul className="list-disc pl-6 mt-1">
                                <li>Type: Persistent Cookies</li>
                                <li>Purpose: Remember Your preferences such as language or region to provide a personalized experience.</li>
                            </ul>
                            <p className="mt-3 sm:mt-4">You may configure Your browser to refuse Cookies. However, some parts of the Service may not function properly without them.</p>
                        </div>

                        <div>
                            <h5>Use of Your Personal Data</h5>
                            <p className="my-3 sm:my-4">ArcLab may use Personal Data for the following purposes:</p>
                            <ul className="list-disc pl-6 mt-1">
                                <li>To provide, operate, and maintain our Service</li>
                                <li>To monitor and analyze Service usage</li>
                                <li>To manage Your Account and registrations</li>
                                <li>To perform contractual obligations and deliver services</li>
                                <li>To contact You via email, phone, or other electronic communications</li>
                                <li>To provide updates, marketing communications, and relevant information (unless You opt out)</li>
                                <li>To manage inquiries and support requests</li>
                                <li>To evaluate or conduct business transfers such as mergers or acquisitions</li>
                                <li>For data analysis, service improvement, and marketing effectiveness</li>
                            </ul>
                        </div>
                        <div>
                            <h5>Sharing of Your Personal Data</h5>
                            <p className="my-3 sm:my-4">We may share Your Personal Data in the following situations:</p>
                            <ul className="list-disc pl-6 mt-1">
                                <li>With Service Providers who assist in operating or analyzing the Service</li>
                                <li>During business transfers, such as mergers or acquisitions</li>
                                <li>With affiliates under common control, who are required to follow this Privacy Policy</li>
                                <li>With business partners for relevant offerings or promotions</li>
                                <li>With other users, if You voluntarily share information in public areas</li>
                                <li>With Your consent, for any other disclosed purpose</li>
                            </ul>
                        </div>
                        <div>
                            <h5>Retention of Your Personal Data</h5>
                            <p className="mt-3 sm:mt-4">ArcLab retains Personal Data only for as long as necessary to fulfill the purposes outlined in this Privacy Policy, comply with legal obligations, resolve disputes, and enforce agreements.</p>
                            <p>Usage Data is generally retained for a shorter duration unless required for security, functionality improvements, or legal compliance.</p>
                        </div>
                        <div>
                            <h5>Transfer of Your Personal Data</h5>
                            <p className="mt-3 sm:mt-4">Your information may be processed and stored in locations where ArcLab or its Service Providers operate. Data protection laws in these locations may differ from those in Your jurisdiction.</p>
                            <p>By submitting Your information, You consent to such transfers. We take reasonable steps to ensure appropriate safeguards are in place to protect Your data.</p>
                        </div>
                        <div>
                            <h5>Delete Your Personal Data</h5>
                            <p className="mt-3 sm:mt-4">You have the right to request deletion of Your Personal Data. You may update, correct, or delete Your information by accessing Your Account settings or by contacting Us directly.</p>
                            <p>We may retain certain information where required by law or for legitimate business purposes.</p>
                        </div>
                        <div>
                            <h5>Disclosure of Your Personal Data</h5>
                            <p className="my-3 sm:my-4">Business Transactions</p>
                            <p>We may retain certain information where required by law or for legitimate business purposes.</p>
                        </div>
                        <div>
                            <h5>Law Enforcement and Legal Requirements</h5>
                            <p className="mt-3 sm:mt-4">We may disclose Personal Data if required to do so by law or in response to valid legal requests, or when necessary to:</p>
                            <ul className="list-disc pl-6 mt-1">
                                <li>Comply with legal obligations</li>
                                <li>Protect the rights or property of ArcLab</li>
                                <li>Prevent or investigate wrongdoing</li>
                                <li>Protect the safety of users or the public</li>
                                <li>Defend against legal liability</li>
                            </ul>
                        </div>
                        
                        <div>
                            <h5>Security of Your Personal Data</h5>
                            <p className="my-3 sm:my-4">We take commercially reasonable measures to protect Your Personal Data. However, no method of transmission over the Internet or electronic storage is completely secure, and we cannot guarantee absolute security.</p>
                        </div>
                        <div>
                            <h5>Children’s Privacy</h5>
                            <p className="my-3 sm:my-4">Our Service does not address individuals under the age of 13. We do not knowingly collect Personal Data from children under 13 without parental consent. If such data is discovered, we will take steps to remove it promptly.</p>
                        </div>
                        <div>
                            <h5>Links to Other Websites</h5>
                            <p className="my-3 sm:my-4">Our Service may contain links to third-party websites not operated by Us. We are not responsible for the privacy practices or content of those websites and encourage You to review their privacy policies.</p>
                        </div>
                        <div>
                            <h5>Changes to This Privacy Policy</h5>
                            <p className="my-3 sm:my-4">We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated “Last updated” date. Significant changes may also be communicated via email or prominent notices on our Service.</p>
                        </div>
                        <div>
                            <h5>Contact Us</h5>
                            <p className="mt-3 sm:mt-4">If You have any questions about this Privacy Policy or our data practices, please contact Us:</p>
                            <p>Email: <Link href="mailto:info@beyondcode.ae">info@beyondcode.ae</Link></p>
                            
                        </div>
                    </div>
                </div>
            </section>
        </>
    );
}


