import Footer from "@/components/footer/footerSection";
import Header from "@/components/header/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Beyond Case Study",
    description: "Generated by create next app",
};

export default function AboutUsLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header />
                {children}
            <Footer />
        </>
    );
}
